FEATURE_LABELS_L2 = {
    "total_crime_est": "Total Crime Index",
    "burglary_crime_est": "Burglary Crime Index",
    "total_population": "Total Population",
    "unemployment_rate_idx": "Unemployment Rate (index)",
    "pct_household_disability": "Households with Disability (%)",
    "pct_public_assistance": "Public Assistance Income (%)",
    "pct_below_poverty": "Below Poverty Level (%)",
    "ACSHHPBLPV_P": "Households Below Poverty (%)",
    "pct_severe_rent_burden": "Severe Rent Burden (%)",
    "pct_no_schooling": "No Schooling Completed (%)",
    "pct_no_health_insurance": "Pop. 35-64 with No Health Insurance (%)",
    "pct_veterans": "Veteran Population (%)",
    "pct_veterans_2": "Veteran Population, 2nd Estimate (%)",
    "pct_hs_grad": "High School Graduate (%)",
    "esri_market_idx_14068_forecast": "Credit Card Debt (market index, forecast)",
    "hospital_count": "Hospitals",
    "fire_station_count": "Fire Stations",
    "library_count": "Libraries",
    "college_count": "Colleges",
    "public_school_count": "Public Schools",
    "private_school_count": "Private Schools",
    "lausd_school_site_count": "LAUSD School Sites",
    "recreation_center_count": "Recreation Centers",
    "adult_recreation_count": "Adult Recreation Sites",
    "affordable_housing_count": "Affordable Housing Sites",
    "sud_treatment_count": "Substance-Use Treatment Centers",
    "business_sites_count": "Business Sites",
    "police_station_count": "Police Stations",
    "food_access_count": "Food Access Sites",
    "transit_stops_count": "Transit Stops",
    "osm_amenity_count": "OSM Amenities",
    "nearest_osm_major_road_m": "Distance to Nearest Major Road (m)",
    "freeway_segments_count": "Freeway Segments",
    "nearest_freeway_m": "Distance to Nearest Freeway (m)",
    "river_drainage_segments_count": "River/Drainage Segments",
    "nearest_river_drainage_m": "Distance to Nearest Waterway (m)",
    "fema_flood_hazard_area_pct": "FEMA Flood Hazard Area (%)",
    "fema_flood_hazard_intersects": "FEMA Flood Hazard (intersects)",
    "la_geohub_100yr_flood_area_pct": "100-Yr Flood Plain Area (%)",
    "la_geohub_100yr_flood_intersects": "100-Yr Flood Plain (intersects)",
    "la_geohub_500yr_flood_area_pct": "500-Yr Flood Plain Area (%)",
    "la_geohub_500yr_flood_intersects": "500-Yr Flood Plain (intersects)",
    "la_geohub_fire_hazard_area_pct": "Fire Hazard Severity Area (%)",
    "tree_canopy_proxy_pct": "Tree Canopy Coverage (%)",
    "water_proxy_pct": "Water Coverage (%)",
    "bare_ground_proxy_pct": "Bare Ground Coverage (%)",
    "dominant_landcover_class": "Dominant Land Cover Class",
    # 0.25mi-only raw Esri alias columns (see train_snn2.QUARTER_ALIASES)
    "2024 Total Crime Index": "Total Crime Index (Esri)",
    "2024 Total Population": "Total Population (Esri)",
    "2024 Unemployment Rate: Index": "Unemployment Rate (Esri index)",
    "2023 HHs w/1+ Persons w/Disability (ACS 5-Yr): Percent": "Households w/ Disability (ACS)",
    "2023 HHs w/Public Assist Income (ACS 5-Yr): Percent": "Public Assist Income (ACS)",
    "2023 Pop w/Income Below Poverty Level (ACS 5-Yr): Percent": "Below Poverty Level (ACS)",
    "2023 HHs/Gross Rent 50+% of Income (ACS 5-Yr): Percent": "Severe Rent Burden (ACS)",
    "2023 Pop 25+: No Schooling (ACS 5-Yr): Percent": "No Schooling (ACS)",
    "2023 Pop 35-64: No Health Insurance (ACS 5-Yr): Percent": "No Health Insurance (ACS)",
    "2023 Civilian Pop 18+: Veteran (ACS 5-Yr): Percent": "Veteran Population (ACS)",
    "2023 Pop 25+: HS Diploma (ACS 5-Yr): Percent": "HS Diploma (ACS)",
    "2030 Value of Credit Card Debt: Index": "Credit Card Debt (Esri index)",
}

FEATURE_GROUPS_L2 = {
    "total_crime_est": "Socioeconomic",
    "burglary_crime_est": "Socioeconomic",
    "total_population": "Socioeconomic",
    "unemployment_rate_idx": "Socioeconomic",
    "pct_household_disability": "Socioeconomic",
    "pct_public_assistance": "Socioeconomic",
    "pct_below_poverty": "Socioeconomic",
    "ACSHHPBLPV_P": "Socioeconomic",
    "pct_severe_rent_burden": "Socioeconomic",
    "pct_no_schooling": "Socioeconomic",
    "pct_no_health_insurance": "Socioeconomic",
    "pct_veterans": "Socioeconomic",
    "pct_veterans_2": "Socioeconomic",
    "pct_hs_grad": "Socioeconomic",
    "esri_market_idx_14068_forecast": "Socioeconomic",

    "hospital_count": "Facilities / Services",
    "fire_station_count": "Facilities / Services",
    "library_count": "Facilities / Services",
    "college_count": "Facilities / Services",
    "public_school_count": "Facilities / Services",
    "private_school_count": "Facilities / Services",
    "lausd_school_site_count": "Facilities / Services",
    "recreation_center_count": "Facilities / Services",
    "adult_recreation_count": "Facilities / Services",
    "affordable_housing_count": "Facilities / Services",
    "sud_treatment_count": "Facilities / Services",
    "business_sites_count": "Facilities / Services",
    "police_station_count": "Facilities / Services",
    "food_access_count": "Facilities / Services",
    "transit_stops_count": "Facilities / Services",
    "osm_amenity_count": "Facilities / Services",

    "nearest_osm_major_road_m": "Roads / Waterways",
    "freeway_segments_count": "Roads / Waterways",
    "nearest_freeway_m": "Roads / Waterways",
    "river_drainage_segments_count": "Roads / Waterways",
    "nearest_river_drainage_m": "Roads / Waterways",

    "fema_flood_hazard_area_pct": "Flood / Hazard",
    "fema_flood_hazard_intersects": "Flood / Hazard",
    "la_geohub_100yr_flood_area_pct": "Flood / Hazard",
    "la_geohub_100yr_flood_intersects": "Flood / Hazard",
    "la_geohub_500yr_flood_area_pct": "Flood / Hazard",
    "la_geohub_500yr_flood_intersects": "Flood / Hazard",
    "la_geohub_fire_hazard_area_pct": "Flood / Hazard",

    "tree_canopy_proxy_pct": "Land Cover",
    "water_proxy_pct": "Land Cover",
    "bare_ground_proxy_pct": "Land Cover",
    "dominant_landcover_class": "Land Cover",
    # 0.25mi-only raw Esri alias columns -- same real-world meaning as
    # their derived counterparts above, so grouped identically
    "2024 Total Crime Index": "Socioeconomic",
    "2024 Total Population": "Socioeconomic",
    "2024 Unemployment Rate: Index": "Socioeconomic",
    "2023 HHs w/1+ Persons w/Disability (ACS 5-Yr): Percent": "Socioeconomic",
    "2023 HHs w/Public Assist Income (ACS 5-Yr): Percent": "Socioeconomic",
    "2023 Pop w/Income Below Poverty Level (ACS 5-Yr): Percent": "Socioeconomic",
    "2023 HHs/Gross Rent 50+% of Income (ACS 5-Yr): Percent": "Socioeconomic",
    "2023 Pop 25+: No Schooling (ACS 5-Yr): Percent": "Socioeconomic",
    "2023 Pop 35-64: No Health Insurance (ACS 5-Yr): Percent": "Socioeconomic",
    "2023 Civilian Pop 18+: Veteran (ACS 5-Yr): Percent": "Socioeconomic",
    "2023 Pop 25+: HS Diploma (ACS 5-Yr): Percent": "Socioeconomic",
    "2030 Value of Credit Card Debt: Index": "Socioeconomic",
}

# Only Facilities/Services counts are realistic policy levers -- everything
# else (socioeconomic indicators, distances to roads/waterways, flood/fire
# hazard exposure, land cover) describes a place rather than something a
# planner can directly build or change.
ACTIONABLE_GROUPS_L2 = {"Facilities / Services"}

GROUP_ORDER_L2 = ["Socioeconomic", "Facilities / Services", "Roads / Waterways", "Flood / Hazard", "Land Cover"]


def interaction_label(a: str, b: str) -> str:
    return f"{FEATURE_LABELS_L2.get(a, a)} \u00d7 {FEATURE_LABELS_L2.get(b, b)}"


RESOLUTION_LABELS = {
    "quarter": "0.25 mile hexagons (finest)",
    "half": "0.50 mile hexagons",
    "three_fourth": "0.75 mile hexagons (coarsest)",
}
